### ISSUE TITLE
Use LB hostnames as weighted CNAME targets

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#182]
**Problem**
Currently if we hit a LB with a hostname, we resolve the IP addresses and use those as A records. This works but this is not ideal as if the IPs behind that hostname change we wont pick them up.  
While we can add a watch for IP changes, this should probably not be the default behaviour as it has some drawbacks
-  It could take several minutes to pick up the change and for the DNS change  to reach clients. 
-  Additionally, if the host resolves to multiple IPs we currently give these equal weight but are not actually different clusters.
-  Finally having watches running uses up additional resources  

**Solution**

If all the clusters for a given gateway are using LB with hostnames, we should default to structuring the DNS records to be multiple weighted CNAMES 
![Screenshot 2023-05-08 at 09 34 10](https://user-images.githubusercontent.com/304628/236785448-8f4608de-c9cb-458c-a34a-a2975ab1cae8.png)
If there is a mix of clusters where a gateway has been deployed with some using an IP as the LB and some using a hostname, we will have to fall back to using just A records as you cannot mix weighted record types (at least in AWS)

Note: 
- This is also how we achieved GEO based DNS setup in previous iterations (glbc)
- If a cluster admin were trying to manage this themselves they would have a similar problem if they mixed IPs and hostnames in their cluster LBs. It is not by using MGC that this problem occurs.

**Note**

I have tested this on AWS but we would want to also figure out what is possible with Azure and Google DNS. 

Note: currently our GetAddress method, only works with IPs so this will need to be changed to deal with hosts also

**Comment by maleck13** [comment]
@mikenairn @roivaz FYI

**Comment by philbrookes** [comment]
as we cannot mix CNAMEs and A records for a weighted DNS record. When a mix is required, we could generate a (or use a premade e.g. nip.io) CNAME for the IP address we want to include, allowing the mix to function. 

Most likely, the ideal approach is to always convert A records to CNAMEs in this manner, so that if a CNAME is required later it can be added.

**Comment by maleck13** [comment]
this is the DNSRecord resource we want to create 

```
apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  name: cname-weighted
  namespace: multi-cluster-gateways
spec:
  managedZone:
    name: mgc-dev-mz
  endpoints:
    - dnsName: test.cb.hcpapps.net
      recordTTL: 60
      recordType: CNAME
      setIdentifier: lb1.example.com
      providerSpecific:
       - name: aws/weight
         value: "120"
      labels:
        id: lb1.example.com
      targets:
        - lb1.example.com
    - dnsName: test.cb.hcpapps.net
      recordTTL: 60
      recordType: CNAME
      setIdentifier: lb2.example.com
      providerSpecific:
       - name: aws/weight
         value: "120"
      labels:
        id: lb2.example.com
      targets:
        - lb2.example.com        

```

**Comment by mikenairn** [comment]
> this is the DNSRecord resource we want to create

This makes sense for hostname only scenarios, but since you can't mix CANME and A records with the same host (https://github.com/Kuadrant/multicluster-gateway-controller/issues/182#issuecomment-1571873094) do we want to consider creating a CNAME and A record for IP addresses and make that the default in all cases:

```
  endpoints:
    - dnsName: test.cb.hcpapps.net
      recordTTL: 60
      recordType: CNAME
      setIdentifier: lb1.example.com
      providerSpecific:
        - name: "aws/weight"
          value: "120"
      labels:
        id: lb1.example.com
      targets:
        - lb1.example.com
    - dnsName: test.cb.hcpapps.net
      recordTTL: 60
      recordType: CNAME
      setIdentifier: lb2.example.com
      providerSpecific:
        - name: "aws/weight"
          value: "120"
      labels:
        id: lb2.example.com
      targets:
        - lb2.example.com
    - dnsName: test.cb.hcpapps.net
      recordTTL: 60
      recordType: CNAME
      setIdentifier: test.127.0.0.1.mn.hcpapps.net
      providerSpecific:
        - name: "aws/weight"
          value: "120"
      labels:
        id: test.127.0.0.1.mn.hcpapps.net
      targets:
        - test.127.0.0.1.mn.hcpapps.net
    - dnsName: test.127.0.0.1.mn.hcpapps.net
      recordTTL: 60
      recordType: A
      setIdentifier: 127.0.0.1
      labels:
        id: 127.0.0.1
      targets:
        - 127.0.0.1
```

**Comment by maleck13** [comment]
I see so this would only be needed if there was a mix of hosts and IPs. If it was all IPs we would just use A records, if it was all hosts we would just use CNAME as I outlined. This  `test.127.0.0.1.cb.hcpapps.net` is effectively a made up host to allow us to mix the two. 
not ideal, but seems better than hacing to setup watches on hostnames so we can use the IPAddresses

**Comment by mikenairn** [comment]
> I see so this would only be needed if there was a mix of hosts and IPs. If it was all IPs we would just use A records, if it was all hosts we would just use CNAME as I outlined. This `test.127.0.0.1.cb.hcpapps.net` is effectively a made up host to allow us to mix the two. not ideal, but seems better than hacing to setup watches on hostnames so we can use the IPAddresses

Or just do it all the time for IP addresses,  we could always create CNAME records for the managed host instead of doing different things if we happen to have a mix. hostname -> create CNAME, ip -> create dedicated A record and CNAME

**Comment by maleck13** [comment]
yeah although that doubles the amount of records we need for hosts that already have IPs and doubles the  number of look ups as each time a CNAME is encountered it triggers a fresh query

**Comment by mikenairn** [comment]
> yeah although that doubles the amount of records we need for hosts that already have IPs and doubles the number of look ups as each time a CNAME is encountered it triggers a fresh query

Maybe, but the CNAMEs could have a fairly large TTL i would say. As for the number of records, yes you are increasing them, but not by much really. We would essentially be creating an lb CNAME per gateway, if it has multiple IPs. that could just be a single A record with multiple values rather than multiple A records since we don't need to worry about balancing those ips. We probably wouldn't want an ip specific CNAME, but a generated one:

```
    - dnsName: test.cb.hcpapps.net
      recordTTL: 300
      recordType: CNAME
      setIdentifier: 12345678987654321.cb.hcpapps.net
      providerSpecific:
        - name: "aws/weight"
          value: "120"
      labels:
        id: 12345678987654321.cb.hcpapps.net
      targets:
        - 12345678987654321.cb.hcpapps.net
    - dnsName: 12345678987654321.cb.hcpapps.net
      recordTTL: 60
      recordType: A
      setIdentifier: 12345678987654321.cb.hcpapps.net
      labels:
        id: 12345678987654321.cb.hcpapps.net
      targets:
        - 127.0.0.1
        - 127.0.0.2
        - 127.0.0.3
```
