### ISSUE TITLE
bug: A record weighting is incorrect

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#192]
setting up two clusters we end up with the following DNS record

```
spec:
    endpoints:
    - dnsName: api.cb.hcpapps.net
      providerSpecific:
      - name: aws/weight
        value: "120"
      recordTTL: 60
      recordType: A
      setIdentifier: 172.32.200.0
      targets:
      - 172.32.200.0
    - dnsName: api.cb.hcpapps.net
      providerSpecific:
      - name: aws/weight
        value: "60"
      recordTTL: 60
      recordType: A
      setIdentifier: 172.32.201.0
      targets:
      - 172.32.201.0
    managedZone:
      name: mctc-dev-mz
```

The weight applied here by default should be the same to allow a round robin type load balancing.
