### ISSUE TITLE
How to install the data plane components

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#427]
**What**

Create a how-to document under the how-to sections of https://docs.kuadrant.io/multicluster-gateway-controller/  that covers how to install the kuadrant data plane components via OCM hub

The usecase here is:  `As a cluster admin , with an existing cluster I wan to use to try kuadrant, how can I install the dataplane components into my spoke cluster. `

steps should be something like:

1) OCM should be installed and you should have an existing OCM hub cluster (we should cover the specifics of that setup in the cp install guide which this should link to) with the control plane components installed (IE follow the CP guide first)
2) Install Istio version x.y as this is the gateway provider and we do not install this (we can provide a ref set of install steps)
3) Install OLM as the service protection components are delivered by OLM currently 
4) Ensure this cluster is added as a managed cluster to your OCM hub (can be same cluster or another)
5) create the `ManagedClusterAddon` resource in the managed cluster namespace to trigger the install of kuadrant into the spoke cluster
```
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
 name: kuadrant-addon
 namespace: kind-mgc-workload-1
spec:
 installNamespace: open-cluster-management-agent-addon
```

https://github.com/Kuadrant/multicluster-gateway-controller/tree/main/config/kuadrant/deploy/hub

https://docs.kuadrant.io/multicluster-gateway-controller/docs/how-to/kuadrant-addon-walkthrough/

are resources that should help here
