### ISSUE TITLE
I should be able to follow the installation guide and install Kuadrant into an existing OpenShift cluster that meets version and dependency requirements.

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#483]
**What**

Follow https://docs.kuadrant.io/multicluster-gateway-controller/docs/installation/control-plane-installation/ and install Kuadrant into an existing OpenShift Cluster that meets the minimum requirements

Bugs should be created as issues and linked to this one

**Comment by david-martin** [comment]
#538

**Comment by david-martin** [comment]
Guide followed successfully on an Openshift cluster.
I installed ocm in the cluster, while just using the `local-cluster` (so 1 cluster).
I did run in to the 2 issues above, which I was able to work around.

I set up a secret and managed zone for both GCP and AWS.
The changed the managedzone name GCP to `mgc-dev-mz-gcp` to avoid conflicting with the AWS one.
```
kubectl get managedzone  -n multi-cluster-gateways  --context ${CTX_HUB_CLUSTER}
NAME             DOMAIN NAME                   ID                                 RECORD COUNT   NAMESERVERS                                                                                                                             READY
mgc-dev-mz       dm.hcpapps.net                /hostedzone/Z0874284GX39ZQKOCETU   8              ["ns-1905.awsdns-46.co.uk","ns-295.awsdns-36.com","ns-797.awsdns-35.net","ns-1366.awsdns-42.org"]                                       True
mgc-dev-mz-gcp   davmarti.google.hcpapps.net   davmarti-google-hcpapps-net        2              ["ns-cloud-b1.googledomains.com.","ns-cloud-b2.googledomains.com.","ns-cloud-b3.googledomains.com.","ns-cloud-b4.googledomains.com."]   True
```
This shouldn't be a problem for following the guide normally though as I'd expect users to choose 1 or the other dns provider, not both (at least not while trying it out).

After getting to the end of the guide I ran some extra steps to verify the dns provider integration.
Usually this could be done by creating a Gateway, HTTPRoute and DNSPolicy.
However, the guide doesn't cover that (or link to it in the next steps. The next steps links to security protection)
Instead, I created a DNSRecord manually for either provider, then verified it got createad in the GCP and AWS consoles.
Here's the records for either:

```yaml
apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  name: myapp.dm.hcpapps.net
spec:
  managedZone:
    name: mgc-dev-mz
  endpoints:
    - dnsName: myapp.dm.hcpapps.net
      recordTTL: 60
      recordType: A
      targets:
        - 172.31.0.1
---
apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  name: myapp.davmarti.google.hcpapps.net
spec:
  managedZone:
    name: mgc-dev-mz-gcp
  endpoints:
    - dnsName: myapp.davmarti.google.hcpapps.net
      recordTTL: 60
      recordType: A
      setIdentifier: 172.31.0.1
      providerSpecific:
        - name: "google/weight"
          value: "120"
      labels:
        id: 172.31.0.1
      targets:
        - 172.31.0.1
```
