### ISSUE TITLE
DNSPolicy using AWS Route53

### ISSUE THREAD

**Issue by philbrookes** [Kuadrant/multicluster-gateway-controller#501]
# Environment set up
- Follow the [quick-start guide](https://docs.kuadrant.io/multicluster-gateway-controller/docs/getting-started/), using the `MGC_BRANCH=<release-branch>` environment variable to the end of: [multicluster gateways walkthrough](https://docs.kuadrant.io/multicluster-gateway-controller/docs/how-to/multicluster-gateways-walkthrough/) and choose `aws` as the DNS Provider.

# Verification Steps
### Default weight is applied
- [x] Look at the DNS Records created in Route53 and confirm they all have the same weighting set as defaults: 120

### Specified default weight is applied
- Edit the DNS Policy to add a custom weight value, in the spec add:
```
  loadBalancing:
    weighted:
      defaultWeight: 100
      custom:
        - weight: 255
          selector:
            matchLabels:
              kuadrant.io/lb-attribute-custom-weight: AWS
        - weight: 10
          selector:
            matchLabels:
              kuadrant.io/lb-attribute-custom-weight: GCP
```
- [x] Check in Route53 that the weighting has been updated to 100.

### Labels are applied and do not affect other clusters
- Label workload1 cluster with AWS label:
```
kubectl label --overwrite managedcluster kind-mgc-workload-1 kuadrant.io/lb-attribute-custom-weight=AWS
```
- [x] Check in Route53 that workload1 has weight 255.
- [x] Check in Route53 that control-plane cluster still has the default 100.

### multiple labels apply different values
- Label control-plane cluster with GCP label (it is OK that this is not actually in GCP):
```
kubectl label --overwrite managedcluster kind-mgc-control-plane kuadrant.io/lb-attribute-custom-weight=GCP
```
- [x] Check in Route53 that the control-plane DNS record has a weight of 10.
- [x] Check in Route53 that the workload1 DNS record has a weight of 255.

### Removal of label resets default value and does not impact existing labels
- Remove Label on workload1:
```
kubectl label --overwrite managedcluster kind-mgc-workload-1 kuadrant.io/lb-attribute-custom-weight-
```
- [x] Check in Route53 that the workload-1 cluster has default weight of 100
- [x] Check in Route53 that the control-plane cluster has a weight of 10

### Removal of all labels resets all weight values to default
- Remove Label on control-plane:
```
kubectl label --overwrite managedcluster kind-mgc-control-plane kuadrant.io/lb-attribute-custom-weight-
```
- [x] Check in Route53 that both clusters have the default weight of 100

### Removal of specified default weight restores general default value.
- Remove the entire loadbalancing section from the spec of the dns policy
- [x] Check in Route53 that both clusters have the default weight of 120

### Add health check section
```
  healthCheck:
    additionalHeadersRef:
      name: probe-headers
    allowInsecureCertificates: true
    endpoint: /
    expectedResponses:
    - 200
    - 201
    - 301
    failureThreshold: 1
    port: 443
    protocol: https
```
- [x] See an error that the additional headers secret is missing
- [x] Create the additionalHeaders secret in the same namespace as the policy
```bash
kubectl create -f - <<EOF
apiVersion: v1
data:
  test_header: dGVzdA==
kind: Secret
metadata:
  name: probe-headers
  namespace: multi-cluster-gateways
EOF
```
- [x] See that health check probe CRs are created for each endpoint on each cluster
- [x] See that the health check probes reference the additional headers secret
- [x] Delete the additionalheaders ref
- [x] Delete the secret
- [x] See that the health check probes still exist
- [x] See that they no longer reference the secret
### Unhealthy endpoints are detected and acted on
- [x] Scale down the workload on one cluster
```bash
kubectl --context kind-mgc-workload-1 scale deployment echo --replicas=0
```
```yaml
  status:
    consecutiveFailures: 4
    healthy: false
    lastCheckedAt: "2023-09-15T14:47:07Z"
    reason: 'Status code: 503'
    status: 503
```
- [x] Wait for the relevant probe to update and show unhealthy
- [x] See that the related  DNS Record is updated to remove the unhealthy IP
- [x] See that the related DNS Record is no longer included in AWS Route53 DNS
- [x] Temporarily scale the deployment back up once again, see the DNS record added once more, and observe the check status go healthy once more
```bash
kubectl --context kind-mgc-workload-1 scale deployment echo --replicas=1
```
```yaml
  status:
    healthy: true
    lastCheckedAt: "2023-09-15T14:52:02Z"
    status: 200
```
- [x] Scale down to 0 once more for the next bit.
```bash
kubectl --context kind-mgc-workload-1 scale deployment echo --replicas=0
```
### Removal of health checks
- [x] Remove the health checks section from the DNS Policy
- [x] see the health check probes are deleted
- [x] see the unhealthy IP address is re-added to the DNS Record
- [x] see the unhealthy IP address is re-added to AWS Route53 DNS
### Removal of listener from gateway
- [x] Remove the listener from the gateway (I'm going to assume this meant "delete the gateway")
```bash
kubectl delete gateway prod-web -n multi-cluster-gateways
```
- [x] see that the related DNS Records are removed
- [x] see that the related DNS Records in AWS Route53 DNS are removed
### Removal of entire DNS Policy
- [x] Delete the DNS Policy
```bash
kubectl delete dnspolicy prod-web -n multi-cluster-gateways
```
- [x] See the related DNS Record CR removed
- [x] See all dns records are removed from AWS Route53 DNS

**Comment by jasonmadigan** [comment]
@philbrookes re "Create the additionalHeaders secret in the same namespace as the policy". Is there an example of the form of this secret? I've checked the docs and I'm a bit lost.

**Comment by jasonmadigan** [comment]
```yaml
kubectl create -f - <<EOF
apiVersion: v1
data:
  test_header: dGVzdA==
kind: Secret
metadata:
  name: probe-headers
  namespace: multi-cluster-gateways
EOF
```

**Comment by jasonmadigan** [comment]
" Remove the listener from the gateway" going to assume this meant delete the gateway, as I don't think Gateways can have no listeners.

**Comment by jasonmadigan** [comment]
One odd issue noticed - if a `Gateway` is removed, then re-created, some _very_ strange things happen. Records are not recreated.

**Comment by jasonmadigan** [comment]
Created a follow-up issue re: https://github.com/Kuadrant/multicluster-gateway-controller/issues/566

**Comment by jasonmadigan** [comment]
Follow-up automation issue: https://github.com/Kuadrant/multicluster-gateway-controller/issues/588

**Comment by jasonmadigan** [comment]
Re-testing with `release-0.1.0-er2`

**Comment by jasonmadigan** [comment]
# Environment set up
- Follow the [quick-start guide](https://docs.kuadrant.io/multicluster-gateway-controller/docs/getting-started/), using the `MGC_BRANCH=<release-branch>` environment variable to the end of: [multicluster gateways walkthrough](https://docs.kuadrant.io/multicluster-gateway-controller/docs/how-to/multicluster-gateways-walkthrough/) and choose `aws` as the DNS Provider.

# Verification Steps
### Default weight is applied
- [x] Look at the DNS Records created in Route53 and confirm they all have the same weighting set as defaults: 120

### Specified default weight is applied
- Edit the DNS Policy to add a custom weight value, in the spec add:
```
  loadBalancing:
    weighted:
      defaultWeight: 100
      custom:
        - weight: 255
          selector:
            matchLabels:
              kuadrant.io/lb-attribute-custom-weight: AWS
        - weight: 10
          selector:
            matchLabels:
              kuadrant.io/lb-attribute-custom-weight: GCP
```
- [x] Check in Route53 that the weighting has been updated to 100.

### Labels are applied and do not affect other clusters
- Label workload1 cluster with AWS label:
```
kubectl label --overwrite managedcluster kind-mgc-workload-1 kuadrant.io/lb-attribute-custom-weight=AWS
```
- [x] Check in Route53 that workload1 has weight 255.
- [x] Check in Route53 that control-plane cluster still has the default 100.

### multiple labels apply different values
- Label control-plane cluster with GCP label (it is OK that this is not actually in GCP):
```
kubectl label --overwrite managedcluster kind-mgc-control-plane kuadrant.io/lb-attribute-custom-weight=GCP
```
- [x] Check in Route53 that the control-plane DNS record has a weight of 10.
- [x] Check in Route53 that the workload1 DNS record has a weight of 255.

### Removal of label resets default value and does not impact existing labels
- Remove Label on workload1:
```
kubectl label --overwrite managedcluster kind-mgc-workload-1 kuadrant.io/lb-attribute-custom-weight-
```
- [x] Check in Route53 that the workload-1 cluster has default weight of 100
- [x] Check in Route53 that the control-plane cluster has a weight of 10

### Removal of all labels resets all weight values to default
- Remove Label on control-plane:
```
kubectl label --overwrite managedcluster kind-mgc-control-plane kuadrant.io/lb-attribute-custom-weight-
```
- [x] Check in Route53 that both clusters have the default weight of 100

### Removal of specified default weight restores general default value.
- Remove the entire loadbalancing section from the spec of the dns policy
- [x] Check in Route53 that both clusters have the default weight of 120

### Add health check section
```
  healthCheck:
    additionalHeadersRef:
      name: probe-headers
    allowInsecureCertificates: true
    endpoint: /
    expectedResponses:
    - 200
    - 201
    - 301
    failureThreshold: 1
    port: 443
    protocol: https
```
- [x] See an error that the additional headers secret is missing
- [x] Create the additionalHeaders secret in the same namespace as the policy
```bash
kubectl create secret generic probe-headers \
  --namespace=multi-cluster-gateways \
  --from-literal=test-header=test
```
- [x] See that health check probe CRs are created for each endpoint on each cluster
- [x] See that the health check probes reference the additional headers secret
- [x] Delete the additionalheaders ref
- [x] Delete the secret
- [x] See that the health check probes still exist
- [x] See that they no longer reference the secret
### Unhealthy endpoints are detected and acted on
- [x] Scale down the workload on one cluster
```bash
kubectl --context kind-mgc-workload-1 scale deployment echo --replicas=0
```
```yaml
  status:
    consecutiveFailures: 4
    healthy: false
    lastCheckedAt: "2023-09-15T14:47:07Z"
    reason: 'Status code: 503'
    status: 503
```
- [x] Wait for the relevant probe to update and show unhealthy
- [x] See that the related  DNS Record is updated to remove the unhealthy IP
- [x] See that the related DNS Record is no longer included in AWS Route53 DNS
- [x] Temporarily scale the deployment back up once again, see the DNS record added once more, and observe the check status go healthy once more
```bash
kubectl --context kind-mgc-workload-1 scale deployment echo --replicas=1
```
```yaml
  status:
    healthy: true
    lastCheckedAt: "2023-09-15T14:52:02Z"
    status: 200
```
- [x] Scale down to 0 once more for the next bit.
```bash
kubectl --context kind-mgc-workload-1 scale deployment echo --replicas=0
```
### Removal of health checks
- [x] Remove the health checks section from the DNS Policy
- [x] see the health check probes are deleted
- [x] see the unhealthy IP address is re-added to the DNS Record
- [x] see the unhealthy IP address is re-added to AWS Route53 DNS
### Removal of listener from gateway
- [x] Remove the listener from the gateway (I'm going to assume this meant "delete the gateway")
```bash
kubectl delete gateway prod-web -n multi-cluster-gateways
```
- [x] see that the related DNS Records are removed
- [x] see that the related DNS Records in AWS Route53 DNS are removed
### Removal of entire DNS Policy
- [x] Delete the DNS Policy
```bash
kubectl delete dnspolicy prod-web -n multi-cluster-gateways
```
- [x] See the related DNS Record CR removed
- [x] See all dns records are removed from AWS Route53 DNS
