### ISSUE TITLE
TLSPolicy testing

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#507]
**What**

Pre-req : 
- Existing environment, this can be from the quick start setup but ensure you are using the release branch

`export MGC_BRANCH=<release-branch under test>`

With an environment setup you should also have some form of placement configured with at least 1 ManagedCluster selected

Gist https://gist.github.com/maleck13/11ad810698a78c7e2012e824671d6211 

This will be there by default with the quick start.

You should also have an cert issuer present (with quick start this will be self signed issuer)

**N.B. Useful sample resources in [this guide](https://docs.kuadrant.io/multicluster-gateway-controller/docs/how-to/multicluster-gateways-walkthrough/)**
- [ ] Setup a gateway definition and label it with the placement label `cluster.open-cluster-management.io/placement: [placement name] `
- [ ] Add 3 HTTPS listeners  one wildcard and two non-wildcard and observe the gateway does not get into a programmed state
- [ ] provide a manual secret for one of the listeners (IE create a secret with the defined name)
- [ ] Define a TLSPolicy (see example below) 
- [ ] Validate it is clear from the TLSPolicy status that the policy has succeeded
- [ ] Validate that the gateway is updated with a policyAffected condition
- [ ] Observe the HTTPS secrets are created for any listener without an existing backing secret and are synced to the cluster
- [ ] Observe the HTTPS secrets are not replaced for listeners with existing manual secrets
- [ ] Validate that a wildcard cert was created and a non wildcard (should be able to do this in the browser)
- [ ] With TLSPolicy in place define some additional HTTPS listeners with named secrets, observe these are also created and synced
- [ ] With TLSPolicy in place define a HTTP listener and check no secrets created
- [ ] With TLSPolicy in place delete a HTTPS listener and observe the secrets are cleaned up and the gateway remains available
- [ ] Delete the TLSPolicy and observe only the TLS secrets created by TLSPolicy are removed (the manual one should stay)
- [ ] Set up a LetsEncrypt ClusterIssuer and re create the TLSPolicy using this issuer
- [ ] Observe that we have LE certs secrets and they synced
- [ ] Validate the HTTPs via the browser or curl
- [ ] Define an invalid TLSPolicy IE that references a Issuer that doesn't exists, validate that it is clear from the status what the issue is
- [ ] Define an invalid TLSPolicy IE that references a none existent gateway validate that it is clear from the status what the issue is

**Example TLSPolicy**

```
apiVersion: kuadrant.io/v1alpha1
kind: TLSPolicy
metadata:
  name: prod-web
  namespace: multi-cluster-gateways
spec:
  targetRef:
    name: prod-web
    group: gateway.networking.k8s.io
    kind: Gateway
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: glbc-ca
```

**Comment by laurafitzgerald** [comment]
**AWS Verification**

- [ ] Fresh quickstart setup using aws as the provider.
- [ ] Setup a gateway definition and label it with the placement label `cluster.open-cluster-management.io/placement: [placement name] `
- [ ] Add 3 HTTPS listeners  one wildcard and two non-wildcard and observe the gateway does not get into a programmed state
- [ ] provide a manual secret for one of the listeners (IE create a secret with the defined name)
- [ ] Define a TLSPolicy (see example below) 
- [ ] Validate it is clear from the TLSPolicy status that the policy has succeeded
- [ ] Validate that the gateway is updated with a policyAffected condition
- [ ] Observe the HTTPS secrets are created for any listener without an existing backing secret and are synced to the cluster
- [ ] Observe the HTTPS secrets are not replaced for listeners with existing manual secrets
- [ ] Validate that a wildcard cert was created and a non wildcard (should be able to do this in the browser)
- [ ] With TLSPolicy in place define some additional HTTPS listeners with named secrets, observe these are also created and synced
- [ ] With TLSPolicy in place define a HTTP listener and check no secrets created
- [ ] With TLSPolicy in place delete a HTTPS listener and observe the secrets are cleaned up and the gateway remains available
- [ ] Delete the TLSPolicy and observe only the TLS secrets created by TLSPolicy are removed (the manual one should stay)
- [ ] Set up a LetsEncrypt ClusterIssuer and re create the TLSPolicy using this issuer
- [ ] Observe that we have LE certs secrets and they synced
- [ ] Validate the HTTPs via the browser or curl
- [ ] Define an invalid TLSPolicy IE that references a Issuer that doesn't exists, validate that it is clear from the status what the issue is
- [ ] Define an invalid TLSPolicy IE that references a none existent gateway validate that it is clear from the status what the issue is

**Comment by philbrookes** [comment]
# Testing against GCP
- [ ] Setup a gateway definition and label it with the placement label cluster.open-cluster-management.io/placement: [placement name] 
- [ ] Create a workload
- [ ] Create DNSPolicy
- [ ] Add 3 HTTPS listeners one wildcard and two non-wildcard and observe the gateway does not get into a programmed state
```
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: myapp.pb.google.hcpapps.net
    name: api
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: test-manual-tls-secret
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: All
    hostname: '*.pb.google.hcpapps.net'
    name: wildcard
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - kind: Secret
        name: wildcard-hcpapps-tls
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: All
    hostname: shop.pb.google.hcpapps.net
    name: shop
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - kind: Secret
        name: shop-hcpapps-tls
      mode: Terminate
```
Failed: gateway is programmed
- [ ] provide a manual secret for one of the listeners (IE create a secret with the defined name)
```
kubectl apply -f - << EOF
apiVersion: v1
data:
  ca.crt: <ca>
  tls.crt:  <crt>
  tls.key:  <key>
kind: Secret
metadata:
  name: test-manual-tls-secret
  namespace: multi-cluster-gateways
type: kubernetes.io/tls
EOF
```
- [ ] Define a TLSPolicy
```
kubectl create -f - << EOF
apiVersion: kuadrant.io/v1alpha1
kind: TLSPolicy
metadata:
  name: prod-web
  namespace: multi-cluster-gateways
spec:
  targetRef:
    name: prod-web
    group: gateway.networking.k8s.io
    kind: Gateway
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: glbc-ca
EOF
```
- [ ] Validate it is clear from the TLSPolicy status that the policy has succeeded
- [ ] Validate that the gateway is updated with a policyAffected condition
- [ ] FAILED: gateway has DNS policy affected but no TLS Policy after waiting about 1 minute
- [ ] Observe the HTTPS secrets are created for any listener without an existing backing secret and are synced to the cluster
- [ ] Observe the HTTPS secrets are not replaced for listeners with existing manual secrets
- [ ] Validate that a wildcard cert was created and a non wildcard (should be able to do this in the browser)
- [ ] With TLSPolicy in place define some additional HTTPS listeners with named secrets, observe these are also created and synced
- [ ] With TLSPolicy in place define a HTTP listener and check no secrets created
- [ ] With TLSPolicy in place delete a HTTPS listener and observe the secrets are cleaned up and the gateway remains available
- [ ] Delete the TLSPolicy and observe only the TLS secrets created by TLSPolicy are removed (the manual one should stay)
- [ ] FAILED: manual test secret was deleted.

### Stopped here, decided with @maleck13 that duplicated testing for Route53 and Google DNS is not required.
- [ ] Set up a LetsEncrypt ClusterIssuer and re create the TLSPolicy using this issuer
- [ ] Observe that we have LE certs secrets and they synced
- [ ] Validate the HTTPs via the browser or curl
- [ ] Define an invalid TLSPolicy IE that references a Issuer that doesn't exists, validate that it is clear from the status what the issue is
- [ ] Define an invalid TLSPolicy IE that references a none existent gateway validate that it is clear from the status what the issue is
