### ISSUE TITLE
bug: hub gateway marked as programmed when TLS secret missing

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#509]
related to #507 
**What**

If a TLS secret is specified in the gateway definition but is not present, the controller ignores this and marks the gateway as programmed. 
The Gateway in the hub should not be marked as programmed until all TLS secrets are present.

**Reproduce**

Create a Gateway with HTTPS listener
```
kind: Gateway
metadata:
  name: prod-web
  namespace: multi-cluster-gateways
  labels:
    cluster.open-cluster-management.io/placement: http-gateway
spec:
  gatewayClassName: kuadrant-multi-cluster-gateway-instance-per-cluster
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: specific
    hostname: 'specific.cb.hcpapps.net'
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: specific.cb.hcpapps.net

```

See that the gateway is placed. The downstream gateway provider does not mark the gateway programmed as the secret is missing. The MGC marks the gateway as Programmed 

```
cbrookes-mac:multicluster-gateway-controller maleck13$ k get gateways -A
NAMESPACE                         NAME       CLASS                                                 ADDRESS   PROGRAMMED   AGE
kuadrant-multi-cluster-gateways   prod-web   istio                                                                        98s
multi-cluster-gateways            prod-web   kuadrant-multi-cluster-gateway-instance-per-cluster             True         99s
```
