### ISSUE TITLE
feat: Extend DNSPolicy to add a schedule

### ISSUE THREAD

**Issue by jasonmadigan** [Kuadrant/multicluster-gateway-controller#516]
# What

Use case: I'm a platform engineer, with a large multicluster application. I want more traffic to head to head to Gateways on one particular cluster for a particular amount of time, based on a schedule. This could be because I have extra resources for a period of time that I wish to utilise, or a particular event may be occurring where I want to ferry more traffic to a larger cluster.

This proposal introduces a `schedule` field to the DNSPolicy spec, which allows users to define time periods during which the policy should be applied.

## Goals

* Provide users with the ability to specify when a DNSPolicy should be active
* Offer flexibility in defining schedules, e.g., specific days of the week, times of the day, or even specific dates.

## Proposed Changes

Add a `schedule` field to the DNSPolicy spec:

```yaml
apiVersion: kuadrant.io/v1alpha1
kind: DNSPolicy
metadata:
  name: prod-web
  namespace: multi-cluster-gateways
spec:
  ...
  schedule:
    - days: [Monday, Wednesday, Friday]
      times:
        - start: "08:00"
          end: "17:00"
    - dates: ["2023-12-24", "2023-12-31"]
```

In this example:

* The policy is active on Monday, Wednesday, and Friday from 08:00 to 17:00 UTC.
* Additionally, the policy is active all day on the 24th and 31st of December 2023.

### Fields

* `days`: A list of days in the week when the policy should be active.
* `times`: A list of time intervals during which the policy should be active. Each interval has a start and end time. These should be UTC.
* `dates`: Specific dates on which the policy should be active.

### Behaviour

* If no `schedule` is provided, the DNSPolicy is always active (current behaviour).
* If a `schedule` is provided, the DNSPolicy is only active during the specified days/times/dates.
* If the current time does not match any schedule, the DNSPolicy should be considered inactive.

### Validation
- The `days` field should only accept valid day names (e.g., Monday, Tuesday).
- The `times` field should only accept valid time formats (HH:MM) and the `end` time should be after the `start` time.
- The `dates` field should only accept valid date formats (YYYY-MM-DD).

## Alternatives

An alternative approach to applying scheduled policies would be to leverage Kubernetes CronJobs. A CronJob creates Jobs on a time-based schedule, as specified by the standard cron format. In the context of our use case, a CronJob could be set up to activate or deactivate the DNSPolicy by modifying the relevant Kubernetes resources at the specified times. 

The downside here is that a user would have to manage two resources, with an intersection between the two.

**Comment by jasonmadigan** [comment]
@maleck13 idea I was kicking around after that demo a few weeks back.

**Comment by maleck13** [comment]
Interesting. One immediate question that comes up, is if I don't have a DNSPolicy that is active what is happening with my DNS?

**Comment by jasonmadigan** [comment]
Thought about this a bit. In the simplest case, this would be the equivalent to having no policy at all.

I think in most use-cases, users would probably define a "default" DNSPolicy, whereas scheduled ones would be additive. When ones with schedules are inactive, the behaviour would revert to that of a default DNSPolicy. By default here, I think we'd look at that as part of the same CR (rather than users having to create 2x policies). That does make the spec balloon in complexity a bit, though.

One other consideration is users would probably want some kind of alerting or metrics to be aware of transitions between policies, or when a policy is about to become inactive.

**Comment by jasonmadigan** [comment]
Some sort of example of what I'd been thinking of:

```yaml
apiVersion: kuadrant.io/v1alpha1
kind: DNSPolicy
metadata:
  name: prod-web
  namespace: multi-cluster-gateways
spec:
  targetRef:
    name: prod-web
    group: gateway.networking.k8s.io
    kind: Gateway

  loadBalancingPolicies:
    - name: geoUS
      geo:
        defaultGeo: US
    - name: weightedAWS
      weighted:
        defaultWeight: 120
        custom:
          - weight: 10
            selector:
              matchLabels:
                kuadrant.io/lb-attribute-custom-weight: AWS
    - name: weightedGCP
      weighted:
        defaultWeight: 255
        custom:
          - weight: 255
            selector:
              matchLabels:
                kuadrant.io/lb-attribute-custom-weight: GCP

  schedule:
    - policyName: geoUS
      days: [Monday, Wednesday, Friday]
      times:
        - start: "08:00"
          end: "17:00"
    - policyName: weightedGCP
      dates: ["2023-12-24", "2023-12-31"]

  defaults:
    policyName: weightedAWS
```

This is based on one of the example policies:
```yaml
apiVersion: kuadrant.io/v1alpha1
kind: DNSPolicy
metadata:
  name: prod-web
  namespace: multi-cluster-gateways
spec:
  targetRef:
    name: prod-web
    group: gateway.networking.k8s.io
    kind: Gateway
  loadBalancing:
    geo:
      defaultGeo: US
    weighted:
      defaultWeight: 120
      custom:
        - weight: 10
          selector:
            matchLabels:
              kuadrant.io/lb-attribute-custom-weight: AWS
        - weight: 255
          selector:
            matchLabels:
              kuadrant.io/lb-attribute-custom-weight: GCP
```

of course open to other suggestions
