### ISSUE TITLE
Gateway "current state of the gateway is unknown error"

### ISSUE THREAD

**Issue by pehala** [Kuadrant/multicluster-gateway-controller#525]
On multiple occasions we saw Gateways with status like this:
```
status:
  conditions:
    - lastTransitionTime: '2023-09-13T07:07:49Z'
      message: 'current state of the gateway is unknown error []%!(EXTRA string=)'
      observedGeneration: 1
      reason: Programmed
      status: Unknown
      type: Programmed
```
It happens in multiple different scenarios (notably #420 or missing TLS secret) and usually signals misconfiguration (or to be more precise, any error in controller), however this status makes it really hard to debug as we need to dig deep into the logs to find the culprit.
