### ISSUE TITLE
DNSPolicy is reporting Ready true when failure is occuring based on TLSPolicy failure

### ISSUE THREAD

**Issue by laurafitzgerald** [Kuadrant/multicluster-gateway-controller#573]
### **Steps to reproduce**
Follow https://docs.kuadrant.io/getting-started/ using aws as the provider
export MGC_SUB_DOMAIN=myapp.$MGC_ZONE_ROOT_DOMAIN

Follow https://github.com/Kuadrant/multicluster-gateway-controller/blob/a4a74009517a92049e24ff738cc0f2246fc6c587/docs/tlspolicy/tls-policy.md#lets-encrypt-issuer-for-route53-hosted-domain

Create gateway
```
kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: prod-web
  namespace: multi-cluster-gateways
spec:
  gatewayClassName: kuadrant-multi-cluster-gateway-instance-per-cluster
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: api
    hostname: $MGC_SUB_DOMAIN
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: apps-hcpapps-tls
          kind: Secret
EOF
```
Label Gateway `kubectl --context kind-mgc-control-plane label gateway prod-web "cluster.open-cluster-management.io/placement"="http-gateway" -n multi-cluster-gateways`

Create tlspolicy using Let's Encryt Issuer
```
kubectl apply -f - <<EOF
apiVersion: kuadrant.io/v1alpha1
kind: TLSPolicy
metadata:
  name: prod-web
  namespace: multi-cluster-gateways
spec:
  targetRef:
    name: prod-web
    group: gateway.networking.k8s.io
    kind: Gateway
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: le-production
EOF
```
Create a DNSPolicy
```
kubectl apply -f - <<EOF
apiVersion: kuadrant.io/v1alpha1             
kind: DNSPolicy
metadata:
  name: prod-web
  namespace: multi-cluster-gateways
spec:
  targetRef:
    name: prod-web
    group: gateway.networking.k8s.io
    kind: Gateway     
EOF  
```

### **Results**
See that the secret generated has the name specified in the gateway and a suffix

```
kc get secret -n multi-cluster-gateways
NAME                     TYPE     DATA   AGE
apps-hcpapps-tls-lqk9w   Opaque   1      2m55s
```
See that no dnsrecord is created

```
kc get dnsrecord -A        
No resources found
```
But that the status of the dnspolicy is Ready 
`kc get dnspolicy prod-web -n multi-cluster-gateways -o yaml | yq -r '.status'`
```conditions:
  - lastTransitionTime: "2023-09-19T11:18:43Z"
    message: Gateway is DNS Enabled
    reason: GatewayDNSEnabled
    status: "True"
    type: Ready
observedGeneration: 1
```
