### ISSUE TITLE
TLSPolicy Affected status missing from gateway. 

### ISSUE THREAD

**Issue by laurafitzgerald** [Kuadrant/multicluster-gateway-controller#577]
## **Steps to Reproduce**

- Follow https://docs.kuadrant.io/getting-started/ with the provider of your choice

Create a gateway 
```
kubectl apply -f - <<EOF                                                                                          
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: prod-web
  namespace: multi-cluster-gateways
spec:
  gatewayClassName: kuadrant-multi-cluster-gateway-instance-per-cluster
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: api
    hostname: $MGC_SUB_DOMAIN
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: apps-hcpapps-tls
          kind: Secret
EOF
```

Label gateway with `kubectl label gateway prod-web -n multi-cluster-gateways cluster.open-cluster-management.io/placement=http-gateway`

Create a TLSPolicy 
glbc is fine for this. 
```
kubectl create -f - << EOF
apiVersion: kuadrant.io/v1alpha1
kind: TLSPolicy
metadata:
  name: prod-web
  namespace: multi-cluster-gateways
spec:
  targetRef:
    name: prod-web
    group: gateway.networking.k8s.io
    kind: Gateway
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: glbc-ca
EOF
```

See that status of the gateway doesn't contain a condition `object affected by policy TLSPolicy`
