### ISSUE TITLE
Incorrect status reported in tlspolicy when issuerRef points to an issuer that doesn't exist

### ISSUE THREAD

**Issue by laurafitzgerald** [Kuadrant/multicluster-gateway-controller#581]
**Steps to reproduce non issuer**
Follow https://docs.kuadrant.io/getting-started/
Follow https://docs.kuadrant.io/multicluster-gateway-controller/docs/how-to/multicluster-gateways-walkthrough/ until the creation of the TLSPolicy
Apply a tlspolicy that points to an issuer that doesn't exist
```
spec:
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: something-else
```

Observe status
```
 status:
    conditions:
    - lastTransitionTime: "2023-09-20T09:04:40Z"
      message: Gateway is TLS Enabled
      reason: GatewayTLSEnabled
      status: "True"
      type: Ready
    observedGeneration: 2
```
