### ISSUE TITLE
automate dnspolicy manual testing

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/multicluster-gateway-controller#588]
Automate all these steps if possible (copied from #515)
Steps are checked if they are already included in the existing test at https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/test/integration/dnspolicy_controller_test.go

# Environment set up
- [x] Follow the [quick-start guide](https://docs.kuadrant.io/multicluster-gateway-controller/docs/getting-started/), using the `MGC_BRANCH=<release-branch>` environment variable to the end of: [multicluster gateways walkthrough](https://docs.kuadrant.io/multicluster-gateway-controller/docs/how-to/multicluster-gateways-walkthrough/) and choose `gcp`/`aws` as the DNS Provider.

# Verification Steps
### Default weight is applied
- [x] Look at the DNS Records created in Google Cloud/Route53 and confirm they all have the same weighting set as defaults: 120 (expand the default.lb CNAME record that has Weighted round robin policy)

### Specified default weight is applied
- [x] Edit the DNS Policy to add a custom weight value, in the spec add:
```
  loadBalancing:
    weighted:
      defaultWeight: 100
      custom:
        - weight: 255
          selector:
            matchLabels:
              kuadrant.io/lb-attribute-custom-weight: AWS
        - weight: 10
          selector:
            matchLabels:
              kuadrant.io/lb-attribute-custom-weight: GCP
```
- [ ] Check in Google DNS/Route53 that the weighting has been updated to 100.

### Labels are applied and do not affect other clusters
- [ ] Label workload1 cluster with AWS label:
```
kubectl label --overwrite managedcluster kind-mgc-workload-1 kuadrant.io/lb-attribute-custom-weight=AWS
```
- [ ] Check in Google DNS/Route53 that workload1 has weight 255.
- [ ] Check in Google DNS/Route53 that control-plane cluster still has the default 100.

### multiple labels apply different values
- [ ] Label control-plane cluster with GCP label (it is OK that this is not actually in GCP):
```
kubectl label --overwrite managedcluster kind-mgc-control-plane kuadrant.io/lb-attribute-custom-weight=GCP
```
- [ ] Check in Google DNS/Route53 that the control-plane DNS record has a weight of 10.
- [ ] Check in Google DNS/Route53 that the workload1 DNS record has a weight of 255.

### Removal of label resets default value and does not impact existing labels
- [ ] Remove Label on workload1:
```
kubectl label --overwrite managedcluster kind-mgc-workload-1 kuadrant.io/lb-attribute-custom-weight-
```
- [ ] Check in Google DNS/Route53 that the workload-1 cluster has default weight of 100
- [ ] Check in Google DNS/Route53 that the control-plane cluster has a weight of 10

### Removal of all labels resets all weight values to default
- [ ] Remove Label on control-plane:
```
kubectl label --overwrite managedcluster kind-mgc-control-plane kuadrant.io/lb-attribute-custom-weight-
```
- [ ] Check in Google DNS/Route53 that both clusters have the default weight of 100

### Removal of specified default weight restores general default value.
- [ ] Remove the entire loadbalancing section from the spec of the dns policy
- [ ] Check in Google DNS/Route53 that both clusters have the default weight of 120

### Add health check section
```
  healthCheck:
    additionalHeadersRef:
      name: probe-headers
    allowInsecureCertificates: true
    endpoint: /
    expectedResponses:
    - 200
    - 201
    - 301
    failureThreshold: 1
    port: 443
    protocol: https
```
- [ ] See an error that the additional headers secret is missing
- [ ] Create the additionalHeaders secret in the same namespace as the policy

```shell
kubectl create -f - <<EOF
apiVersion: v1
data:
  test_header: dGVzdA==
kind: Secret
metadata:
  name: probe-headers
  namespace: multi-cluster-gateways
EOF
```

- [x] See that health check probe CRs are created for each endpoint on each cluster
- [ ] See that the health check probes reference the additional headers secret
- [ ] Delete the additionalheaders ref
- [ ] Delete the secret
- [ ] See that the health check probes still exist
- [ ] See that they no longer reference the secret
### Unhealthy endpoints are detected and acted on
- [ ] Scale down the workload on one cluster
- [ ] Wait for the relevant probe to update and show unhealthy
- [ ] See that the related  DNS Record is updated to remove the unhealthy IP
- [ ] See that the related DNS Record is no longer included in Google Cloud/Route53 DNS
### Removal of health checks
- [ ] Remove the health checks section from the DNS Policy
- [ ] see the health check probes are deleted
- [ ] see the unhealthy IP address is re-added to the DNS Record
- [ ] see the unhealthy IP address is re-added to Google Cloud/Route53 DNS
### Removal of listener from gateway
- [ ] Edit the listener hostname in the gateway so it no longer matches the HTTPRoute
- [ ] see that the related DNS Records are removed
- [ ] see that the related DNS Records in Google Cloud/Route53 DNS are removed
- [ ] Edit the listener hostname back to what it was before
- [ ] see that the related DNS Records are recreated
- [ ] see that the related DNS Records in Google Cloud/Route53 DNS are recreated
### Removal of entire DNS Policy
- [x] Delete the DNS Policy
- [ ] See the related DNS Record CR removed
- [ ] see all DNS records are removed from Google Cloud/Route53 DNS
