### ISSUE TITLE
Multiple policy controllers running on a single cluster when hub and spoke are same cluster

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/multicluster-gateway-controller#693]
**What**

In a setup where the hub and spoke are the same cluster, we end up with two policy controllers running.

Installing the kuadrant operator using the OCM addon can result in two policy controllers running on the same cluster more than likely with different versions.

```
make local-setup OCM_SINGLE=true

cat <<EOF | kubectl apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: mgc-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: quay.io/kuadrant/kuadrant-operator-catalog:latest
  grpcPodConfig:
    securityContextConfig: restricted
  displayName: mgc-catalog
  publisher: Red Hat
EOF

kubectl annotate --overwrite managedclusteraddon kuadrant-addon "addon.open-cluster-management.io/values"='{"CatalogSource":"mgc-catalog", "Channel":"preview"}'

make docker-build-gateway-controller kind-load-gateway-controller docker-build-policy-controller kind-load-policy-controller deploy-gateway-controller
```

```
kubectl get deployments -A -n kind-mgc-control-plane | grep policy
kuadrant-system                          kuadrant-operator-policy-controller       1/1     1            1           78m
multicluster-gateway-controller-system   mgc-policy-controller                     1/1     1            1           79m
```

This is only obvious when you use the `OCM_SINGLE` flag and the latest version of kuadrant operator. This will cause issues with our e2e tests when the kuadrant operator is eventually updated in the stable channel.

**Comment by maleck13** [comment]
One option here may be to limit the operator being installed via its operator group to a set of specific namespaces IE the spoke cluster namespaces

```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: my-group
  namespace: my-namespace
spec:
  targetNamespaces:
  - kuadrant-spoke-namespace1
 ```
