### ISSUE TITLE
Investigate custom ingress Gateway and controller

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#73]
**What**

We want to ensure that what we do is compliant with gitops, and also intuative for users who are familiar with kubernetes concepts. Currently we modify ingresses that we see directly. This can cause issues with gitops tools like argoCD. Additionally it can make configuring how to manage these ingresses complex as there may be other controllers and webhook intercepting these ingresses. 

To solve this, we want to explore the idea of creating a custom ingress controller as part of the traffic controller deployment. This ingress controller would define its own ingressClass. While it would be considered an ingress controller it would effectively ensure that ingress was transformed and behaving as expected before delegating the ingress via a copy to a chosen ingress controller that would then use that ingress to configure traffic routing etc. As this copy would be owned by the original, it would be considered a derived resource and so not cause issues with ArgoCD.

This approach means delegating an ingress to traffic controller would mean assigning the right ingressClass to your ingress. 

Additionally as we are looking at defining multi-cluster gateways at the control plane, we potentially could represent this ingress controller via a "virtual gateway" resource at the control plane. Where this resource would configure and trigger the deployment of our ingress controller to the data plane

Ingress Controller

- Sees Ingress
- Checks its listeners config (specified at the control planed and synced down)
- validates that the ingress is good (passes any allowedRoutes rules)
- finds the needed TLS secret for the listener (also in the same ns as the controller) and copies it to the ingress ns
- mutates the ingress and creates a copy of that ingress in the same ns as the target ingress
- The ingress controller can only delegate to one actual ingress controller. The LB for this is what is set in the status of the virtual gateway

```
apiVersion: kudarant.io/v1Alpha1
kind: VirtualGateway
metadata:
  name: example-gateway
spec:
  gatewayClassName: ingress-gateway
  listeners:
  - name: https
    hostname: "*.example.com"
    allowedRoutes:
      kinds: 
        - kind: Ingress
      namespaces:
        from: Selector
        selector:
          matchLabels:
            shared-gateway-access: "true"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: example-com

```
