### ISSUE TITLE
Bug: TLSPolicy controller does not watch ClusterIssuers 

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#730]
**What**

Create a TLSPolicy with no Cluster Issuer present

```
kubectl --context kind-kuadrant-local apply -f - <<EOF
apiVersion: kuadrant.io/v1alpha1
kind: TLSPolicy
metadata:
  name: api-gateway-tls
  namespace: kuadrant-system
spec:
  targetRef:
    name: api-gateway
    group: gateway.networking.k8s.io
    kind: Gateway
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: glbc-ca
EOF
```

You will see a status error in the policy

Create the issuer, the policy does not get reconciled
